category:
  name_max_length: 255
cart:
  max_size: 5
comment:
  maximum_message_length: 1000
gravatar:
  gravatar_image_size: 80
  gravatar_user_image_size: 200
product:
  hot_trend_duration: 2
  limit_hot_trend_product: 10
  max_rating_point: 10
  maximum_description_length: 1000
  maximum_name_length: 255
  maximum_recent_viewed_product: 8
  min_price: 0
  min_quantity: 1
  min_rating_point: 0
rating:
  max_rating_point: 10
  min_rating_point: 0
request:
  max_status: 2
  maximum_length_content: 1000
  min_status: 0
user:
  name_size_max: 50
  email_length: 50
  password_min: 6
will_paginate:
  per_page: 10
  per_page_product: 8
  per_page_order: 5
